# Generated by Django 5.1.6 on 2025-05-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True, 'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители'},
        ),
    ]
